In [1]:
import pandas as pd
df = pd.read_csv('fakenews/train.csv')

df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [2]:

df.dropna()

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [3]:

df = df.dropna()

In [4]:
x = df.drop('label',axis=1)

y = pd.DataFrame(df['label'])

import tensorflow as tf

from keras.layers import Embedding, LSTM, Dense
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.preprocessing.text import one_hot


voc_size = 5000
messages = x.copy()
messages.reset_index(inplace=True)


import nltk
import re
from nltk.corpus import stopwords


nltk.download('stopwords')

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []


messages['title'][0]
#print(messages['title'][53])
#messages = messages.dropna()
for i in range(len(messages)):
    if type(messages['title'][i]) != str:
        print(i)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\saifm\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [5]:
for i in range(len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]',' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
    

1
14952
14953
14954
14955
14956
14957
14958
14959
14960
14961
14962
14963
14964
14965
14966
14967
14968
14969
14970
14971
14972
14973
14974
14975
14976
14977
14978
14979
14980
14981
14982
14983
14984
14985
14986
14987
14988
14989
14990
14991
14992
14993
14994
14995
14996
14997
14998
14999
15000
15001
15002
15003
15004
15005
15006
15007
15008
15009
15010
15011
15012
15013
15014
15015
15016
15017
15018
15019
15020
15021
15022
15023
15024
15025
15026
15027
15028
15029
15030
15031
15032
15033
15034
15035
15036
15037
15038
15039
15040
15041
15042
15043
15044
15045
15046
15047
15048
15049
15050
15051
15052
15053
15054
15055
15056
15057
15058
15059
15060
15061
15062
15063
15064
15065
15066
15067
15068
15069
15070
15071
15072
15073
15074
15075
15076
15077
15078
15079
15080
15081
15082
15083
15084
15085
15086
15087
15088
15089
15090
15091
15092
15093
15094
15095
15096
15097
15098
15099
15100
15101
15102
15103
15104
15105
15106
15107
15108
15109
15110
15111
15112
15113
15114
15115
15116
15117
15

In [6]:
onehot_repr = [one_hot(words,voc_size) for words in corpus]
onehot_repr

912, 254, 2361, 3305, 4952, 4308, 4052, 2076, 2923, 1281],
 [3513, 725, 1226, 2853],
 [4127, 2259, 3296, 451, 3174, 1319, 3415, 3075],
 [3911, 3595, 2382, 1646, 3990, 2747, 2493, 3305, 4716, 2814],
 [4123, 3071, 4635, 1099, 4376, 2717, 4365, 4],
 [4371, 1836, 4371, 4944, 3101, 294],
 [1024, 1357, 306, 726, 4316, 3704, 1791, 1249, 1021, 3305, 4716, 2814],
 [2248, 955, 1196, 136, 4499, 4569, 2810, 3651, 4404, 3305, 4716, 2814],
 [828, 745, 3645, 3829, 1610, 2871, 2277, 2725],
 [4247, 3847, 1196, 1445, 4512, 1447, 771, 4855, 3305, 4716, 2814],
 [2272, 4776, 4155, 366, 528],
 [1333, 1774, 321, 150, 810, 4283, 2939, 4473, 1906, 3305, 4716, 2814],
 [1740, 1689, 3177, 3508, 2303, 2201, 1913, 1009, 375],
 [4723, 4221, 4418, 3646, 3240, 1514, 3513],
 [1951, 254, 3659, 4197, 3513, 2500, 2882, 4404],
 [2191, 4316, 4394, 624, 2624, 2191],
 [3513, 1068, 3428, 1611],
 [151, 4026, 3459, 1913, 2980, 133, 4178, 268, 4, 2191],
 [3995, 2494, 2500, 4080, 2743, 1925, 3513, 3305, 4716, 2814],
 [2915, 893, 4

In [7]:
print(len(onehot_repr[0]))

10


In [8]:
print(len(onehot_repr).max())

AttributeError: &#39;int&#39; object has no attribute &#39;max&#39;

In [9]:

lens = [len(i) for i in onehot_repr[i]]

TypeError: object of type &#39;int&#39; has no len()

In [10]:
onehot_repr[0]

[3234, 162, 2810, 4388, 3765, 2694, 4961, 4192, 3817, 4075]

In [11]:
len(onehot_repr[0])

10

In [12]:
onehot_repr[0].shape

AttributeError: &#39;list&#39; object has no attribute &#39;shape&#39;

In [13]:
onehot_repr[0].shape()

AttributeError: &#39;list&#39; object has no attribute &#39;shape&#39;

In [14]:
len(onehot_repr[0])

10

In [15]:
lens = []
for i in range(len(onehot_repr)):
    lens.append(len(onehot_repr[i]))


In [16]:
lens.mean()

AttributeError: &#39;list&#39; object has no attribute &#39;mean&#39;

In [17]:
mean(lens)

NameError: name &#39;mean&#39; is not defined

In [18]:
from statistics import mean
mean(lens)

8.725731473885698

In [19]:
from statistics import mode
mode(lens)

10

In [20]:
from statistics import mode
max(lens)

47

In [21]:
sent_len = 20
embedded_docs = pad_sequences(onehot_repr, padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0 ... 4192 3817 4075]
 [   0    0    0 ...  498 2484 2191]
 [   0    0    0 ... 4069  576 1682]
 ...
 [   0    0    0 ... 3305 4716 2814]
 [   0    0    0 ... 1779 1597  359]
 [   0    0    0 ... 2079  836 1226]]


In [22]:
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_len))
model.add(LSTM(100)) #one layer with 100 neurons
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])
model.summary()

Model: &quot;sequential&quot;
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [23]:
import numpy as np

In [24]:
x_final = np.array(embedded_docs)
y_final = np.array(y)

In [25]:
x_final.shape, y_final.shape

((18285, 20), (18285, 1))

In [26]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x_final,y_final, test_size = 0.3, random_state=0)


In [27]:
history = model.fit(xtrain,ytrain,validation_data=(xtest,ytest),epochs=25,batch_size=64)

Epoch 1/25
200/200 [==============================] - 2s 12ms/step - loss: 0.3181 - acc: 0.8518 - val_loss: 0.1862 - val_acc: 0.9213
Epoch 2/25
200/200 [==============================] - 2s 11ms/step - loss: 0.1365 - acc: 0.9462 - val_loss: 0.1842 - val_acc: 0.9205
Epoch 3/25
200/200 [==============================] - 2s 10ms/step - loss: 0.0950 - acc: 0.9658 - val_loss: 0.2271 - val_acc: 0.9162
Epoch 4/25
200/200 [==============================] - 2s 10ms/step - loss: 0.0669 - acc: 0.9759 - val_loss: 0.2140 - val_acc: 0.9162
Epoch 5/25
200/200 [==============================] - 2s 10ms/step - loss: 0.0488 - acc: 0.9838 - val_loss: 0.2733 - val_acc: 0.9087
Epoch 6/25
200/200 [==============================] - 2s 10ms/step - loss: 0.0289 - acc: 0.9902 - val_loss: 0.4289 - val_acc: 0.9065
Epoch 7/25
200/200 [==============================] - 2s 10ms/step - loss: 0.0175 - acc: 0.9945 - val_loss: 0.3717 - val_acc: 0.9220
Epoch 8/25
200/200 [==============================] - 2s 10ms/step - 

In [28]:
ypred= model.predict(xtest)

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(ytest,ypred)
acc = accuracy_score(ytest,ypred)

ValueError: Classification metrics can&#39;t handle a mix of binary and continuous targets

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(ytest,ypred)

ValueError: Classification metrics can&#39;t handle a mix of binary and continuous targets

In [31]:
acc = accuracy_score(ytest,ypred)

ValueError: Classification metrics can&#39;t handle a mix of binary and continuous targets

In [32]:
ypred= model.predict(xtest)
ypred1 = np.argmax(ypred)

In [33]:
ypred= model.predict(xtest)
ypred = ypred > 0.5

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(ytest,ypred)

In [35]:
acc = accuracy_score(ytest,ypred)